export const articles = [
    {
        id: 1,
        title: "Understanding the difference between grid-template and grid-auto",
        date: "Oct 09, 2018",
        content: "With all the new properties related to CSS Grid Layout, understanding the difference between grid-template and grid-auto can make your layouts more efficient.",
    },
    {
        id: 2,
        title: "Recreating the GitHub Contribution Graph with CSS Grid",
        date: "Oct 10, 2018",
        content: "How to recreate the GitHub contribution graph using CSS Grid and Flexbox for better compatibility.",
    },
    {
        id: 3,
        title: "10 JavaScript Tricks You Should Know",
        date: "Nov 05, 2021",
        content: "Explore lesser-known JavaScript tips and tricks that can boost your productivity as a developer.",
    },
    {
        id: 4,
        title: "The Future of Web Development in 2024",
        date: "Dec 15, 2023",
        content: "Discover the trends and technologies shaping web development in 2024, including AI-powered tools and new frameworks.",
    },
    {
        id: 5,
        title: "Building Accessible Web Forms",
        date: "Feb 01, 2023",
        content: "A guide to creating web forms that are accessible to users with disabilities, focusing on ARIA roles and semantic HTML.",
    },
    {
        id: 6,
        title: "Improving React App Performance",
        date: "Mar 10, 2023",
        content: "Learn how to optimize your React applications by using memoization, code splitting, and other techniques.",
    },
    {
        id: 7,
        title: "An Introduction to Tailwind CSS",
        date: "Jul 07, 2022",
        content: "Get started with Tailwind CSS, a utility-first CSS framework for rapidly building modern websites.",
    },
    {
        id: 8,
        title: "Understanding TypeScript Generics",
        date: "Sep 18, 2022",
        content: "Learn the basics of TypeScript generics and how they can make your code more reusable and type-safe.",
    },
    {
        id: 9,
        title: "How to Use React Context Effectively",
        date: "Jun 12, 2023",
        content: "Explore the benefits and best practices for managing state using React Context.",
    },
    {
        id: 10,
        title: "The Basics of GraphQL",
        date: "Jan 22, 2022",
        content: "Understand the core concepts of GraphQL and how it differs from traditional REST APIs.",
    },
    {
        id: 11,
        title: "Exploring Node.js Streams",
        date: "Apr 30, 2021",
        content: "Learn how to efficiently process data using streams in Node.js for better performance and scalability.",
    },
    {
        id: 12,
        title: "Creating Custom Hooks in React",
        date: "Oct 15, 2023",
        content: "How to build and use custom hooks to encapsulate reusable logic in your React applications.",
    },
    {
        id: 13,
        title: "Understanding CSS Specificity",
        date: "Nov 27, 2022",
        content: "A complete guide to CSS specificity and how to resolve conflicts in your stylesheets.",
    },
    {
        id: 14,
        title: "Top 5 JavaScript Frameworks for 2024",
        date: "Dec 30, 2023",
        content: "A breakdown of the most popular JavaScript frameworks for 2024 and their unique features.",
    },
    {
        id: 15,
        title: "How to Build a REST API with Express.js",
        date: "May 10, 2021",
        content: "Step-by-step instructions for building a RESTful API using Node.js and Express.js.",
    },
    {
        id: 16,
        title: "Deploying Applications with Docker",
        date: "Aug 20, 2022",
        content: "Learn how to containerize and deploy your applications using Docker for consistent and efficient environments.",
    },
    {
        id: 17,
        title: "Debugging JavaScript: Tips and Tools",
        date: "Jul 05, 2021",
        content: "An overview of the best practices and tools for debugging JavaScript applications.",
    },
    {
        id: 18,
        title: "Writing Tests with Jest",
        date: "Feb 28, 2022",
        content: "How to write unit and integration tests for your JavaScript applications using Jest.",
    },
    {
        id: 19,
        title: "Getting Started with Vue.js 3",
        date: "Sep 10, 2021",
        content: "An introductory guide to building web applications with Vue.js 3, featuring Composition API examples.",
    },
    {
        id: 20,
        title: "State Management with Redux Toolkit",
        date: "Apr 15, 2023",
        content: "Simplify state management in React applications using Redux Toolkit and its powerful features.",
    },
    {
        id: 21,
        title: "Understanding the Virtual DOM",
        date: "Mar 20, 2022",
        content: "Learn what the virtual DOM is and how it makes frameworks like React perform efficiently.",
    },
    {
        id: 22,
        title: "Web Accessibility: A Practical Guide",
        date: "Jun 15, 2022",
        content: "A step-by-step guide to making your websites more accessible for users with diverse abilities.",
    },
    {
        id: 23,
        title: "Next.js vs. Nuxt.js: A Comparison",
        date: "Dec 01, 2023",
        content: "A detailed comparison of Next.js and Nuxt.js, two popular frameworks for server-side rendering.",
    },
    {
        id: 24,
        title: "How to Use Git Effectively",
        date: "Oct 25, 2023",
        content: "A comprehensive guide to mastering Git and improving your version control workflow.",
    },
    {
        id: 25,
        title: "Top 10 CSS Tricks for Better Design",
        date: "Jan 05, 2022",
        content: "Discover ten CSS techniques to improve the design and user experience of your websites.",
    },
];
